app:
  success: 3
  path: csv/
  extension: .csv
  locale-tag: en-US



spring:
  output:
    ansi:
      enabled: always
  messages:
    basename: i18n/messages
  main:
    allow-circular-references: true