spring:
  datasource:
    url: jdbc:h2:mem:librarydb
  main:
    allow-circular-references: true
  liquibase:
    change-log: db.changelog/liquibase-changelog.xml
    drop-first: true
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true