spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: librarydb
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.lyamin.app.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: ERROR

server:
  port: 8080