spring:

  datasource:
    url: jdbc:h2:mem:librarydb
  main:
    allow-circular-references: true
  liquibase:
    enabled: true
    drop-first: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
management:
  endpoints:
    web:
      exposure:
        include: "health, logfile, metrics"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    root: info
  file:
    name: logs/libraryApp.log