spring:
  datasource:
    url: jdbc:h2:mem:librarydb
  main:
    allow-circular-references: true
  sql:
    init:
      schema-locations: schema.sql
      data-locations: data.sql
      mode: always

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true